# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 12:21
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='employee.employee_id', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=300), unique_with=('appraisal',)),
        ),
    ]
