# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-25 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='created',
            new_name='date',
        ),
    ]
