# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0002_auto_20170726_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
