# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 16:06
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0004_auto_20170726_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='this',
            field=django_markdown.models.MarkdownField(blank=True, null=True),
        ),
    ]
